export const CONFIG_DESCRIPTIONS = {
  "API_BASE_URL": "app.notion.com/api/v3', // API默认请求地址,可以配置成自己的地址例如：https://[xxxxx].notion.site/api/v3",
  "THEME": "当前主题，在themes文件夹下可找到所有支持的主题；主题名称就是文件夹名，例如 claude,endspace,example,fukasawa,fuwari,gitbook,heo,hexo,landing,matery,medium,next,nobelium,plog,simple",
  "PSEUDO_STATIC": "伪静态路径，开启后所有文章URL都以 .html 结尾。",
  "NEXT_REVALIDATE_SECOND": "更新缓存间隔 单位(秒)；即每个页面有60秒的纯静态期、此期间无论多少次访问都不会抓取notion数据；调大该值有助于节省Vercel资源、同时提升访问速率，但也会使文章更新有延迟。",
  "REVALIDATION_TOKEN": "On-Demand Revalidation Token，设置后可通过 POST /api/revalidate 立即刷新页面缓存（解决 Notion 内容更新延迟问题）",
  "APPEARANCE": "['light', 'dark', 'auto'], // light 日间模式 ， dark夜间模式， auto根据时间和主题自动夜间模式",
  "APPEARANCE_DARK_TIME": "夜间模式起至时间，false时关闭根据时间自动切换夜间模式",
  "AUTHOR": "您的昵称 例如 tangly1024",
  "BIO": "作者简介",
  "LINK": "tangly1024.com', // 网站地址",
  "KEYWORDS": "网站关键词 英文逗号隔开",
  "BLOG_FAVICON": "blog favicon 配置, 默认使用 /public/favicon.ico，支持在线图片，如 https://img.imesong.com/favicon.png",
  "PWA_ENABLE": "是否启用 PWA 安装入口；也可在 Notion_Config 中配置 PWA_ENABLE=true",
  "PWA_NAME": "PWA 安装名称；默认读取站点标题，通常无需单独配置",
  "PWA_SHORT_NAME": "PWA 短名称；默认读取站点标题，通常无需单独配置",
  "PWA_ICON": "PWA 页面图标（apple-touch-icon / favicon 回退）；不控制 manifest 安装图标，manifest 使用内置尺寸合规的 PNG",
  "PWA_ICON_192": "可选：覆盖 manifest 192x192 普通图标；须提供真实 192×192 尺寸的资源路径",
  "PWA_ICON_512": "可选：覆盖 manifest 512x512 普通图标；须提供真实 512×512 尺寸的资源路径",
  "PWA_ICON_192_MASKABLE": "可选：覆盖 manifest 192x192 maskable 图标；资源应留有足够安全边距",
  "PWA_ICON_512_MASKABLE": "可选：覆盖 manifest 512x512 maskable 图标；资源应留有足够安全边距",
  "PWA_THEME_COLOR": "PWA 主题色",
  "PWA_BACKGROUND_COLOR": "PWA 启动画面背景色",
  "BEI_AN": "备案号 闽ICP备XXXXXX",
  "BEI_AN_LINK": "beian.miit.gov.cn/', // 备案查询链接，如果用了萌备等备案请在这里填写",
  "BEI_AN_GONGAN": "公安备案号，例如 '浙公网安备3xxxxxxxx8号'",
  "ENABLE_RSS": "是否开启RSS订阅功能",
  "CUSTOM_MENU": "支持Menu类型的菜单，替代了3.12版本前的Page类型",
  "CAN_COPY": "是否允许复制页面内容，默认允许；可被文章属性 CAN_COPY / ext.CAN_COPY 覆盖。",
  "ADSENSE_GOOGLE_ID": "谷歌广告ID e.g ca-pub-xxxxxxxxxxxxxxxx",
  "ADSENSE_GOOGLE_TEST": "谷歌广告ID测试模式，这种模式获取假的测试广告，用于开发 https://www.tangly1024.com/article/local-dev-google-adsense",
  "ADSENSE_GOOGLE_SLOT_IN_ARTICLE": "Google AdScene>广告>按单元广告>新建文章内嵌广告 粘贴html代码中的data-ad-slot值",
  "ADSENSE_GOOGLE_SLOT_FLOW": "Google AdScene>广告>按单元广告>新建信息流广告",
  "ADSENSE_GOOGLE_SLOT_NATIVE": "Google AdScene>广告>按单元广告>新建原生广告",
  "ADSENSE_GOOGLE_SLOT_AUTO": "Google AdScene>广告>按单元广告>新建展示广告 （自动广告）",
  "AD_WWADS_ID": "https://wwads.cn/ 创建您的万维广告单元ID",
  "AD_WWADS_BLOCK_DETECT": "是否开启WWADS广告屏蔽插件检测,开启后会在广告位上以文字提示 @see https://github.com/bytegravity/whitelist-wwads",
  "WEB_WHIZ_BASE_URL": "api.webwhiz.ai',",
  "ANALYTICS_VERCEL": "vercel自带的统计 https://vercel.com/docs/concepts/analytics/quickstart https://github.com/notionnext-org/NotionNext/issues/897",
  "ANALYTICS_BUSUANZI_ENABLE": "展示网站阅读量、访问数 see http://busuanzi.ibruce.info/",
  "ANALYTICS_CNZZ_ID": "只需要填写站长统计的id, [cnzz_id] -> https://s9.cnzz.com/z_stat.php?id=[cnzz_id]&web_id=[cnzz_id]",
  "ANALYTICS_GOOGLE_ID": "谷歌Analytics的id e.g: G-XXXXXXXXXX",
  "ANALYTICS_51LA_ID": "id，在51la后台获取 参阅 https://docs.tangly1024.com/article/notion-next-51-la",
  "ANALYTICS_51LA_CK": "ck，在51la后台获取",
  "MATOMO_HOST_URL": "Matomo服务器地址，不带斜杠",
  "MATOMO_SITE_ID": "Matomo网站ID",
  "SEO_GOOGLE_SITE_VERIFICATION": "Remove the value or replace it with your own google site verification code",
  "SEO_BAIDU_SITE_VERIFICATION": "Remove the value or replace it with your own google site verification code",
  "CLARITY_ID": "只需要复制Clarity脚本中的ID部分，ID是一个十位的英文数字组合",
  "UMAMI_HOST": "cloud.umami.is/script.js', // umami的服务地址",
  "UMAMI_ID": "umami的id",
  "FIREWORKS": "开关",
  "MOUSE_FOLLOW": "开关",
  "MOUSE_FOLLOW_EFFECT_TYPE": "1-12",
  "MOUSE_FOLLOW_EFFECT_COLOR": "鼠标点击特效颜色 #xxxxxx 或者 rgba(r,g,b,a)",
  "SAKURA": "开关",
  "NEST": "开关",
  "FLUTTERINGRIBBON": "开关",
  "RIBBON": "开关",
  "STARRY_SKY": "开关",
  "PRISM_JS_PATH": "npm.elemecdn.com/prismjs@1.29.0/components/',",
  "PRISM_JS_AUTO_LOADER": "npm.elemecdn.com/prismjs@1.29.0/plugins/autoloader/prism-autoloader.min.js',",
  "PRISM_THEME_SWITCH": "是否开启浅色/深色模式代码主题切换； 开启后将显示以下两个主题",
  "CODE_MAC_BAR": "代码左上角显示mac的红黄绿图标",
  "CODE_LINE_NUMBERS": "是否显示行号",
  "CODE_COLLAPSE": "是否支持折叠代码框",
  "CODE_COLLAPSE_EXPAND_DEFAULT": "折叠代码默认是展开状态",
  "CODE_COLLAPSE_MIN_LINES": "只有超过该行数的代码块才显示折叠条",
  "COMMENT_HIDE_SINGLE_TAB": "Whether hide the tab when there's no tabs. 只有一个评论组件时是否隐藏切换组件的标签页",
  "COMMENT_ARTALK_SERVER": "ArtalkServert后端地址 https://artalk.js.org/guide/deploy.html",
  "COMMENT_TWIKOO_ENV_ID": "TWIKOO后端地址 腾讯云环境填envId；Vercel环境填域名，教程：https://tangly1024.com/article/notionnext-twikoo",
  "COMMENT_TWIKOO_COUNT_ENABLE": "博客列表是否显示评论数",
  "COMMENT_UTTERRANCES_REPO": "你的代码仓库名， 例如 'username/repository'； 更多文档参考 https://utteranc.es/",
  "COMMENT_GISCUS_REPO": "你的Github仓库名 e.g 'username/repository'",
  "COMMENT_GISCUS_REPO_ID": "你的Github Repo ID e.g ( 設定完 giscus 即可看到 )",
  "COMMENT_GISCUS_CATEGORY": "你的Github Discussions 內的 Category 名称 e.g 'General' ( 設定完 giscus 即可看到 )",
  "COMMENT_GISCUS_CATEGORY_ID": "你的Github Discussions 內的 Category ID ( 設定完 giscus 即可看到 )",
  "COMMENT_GISCUS_MAPPING": "你的Github Discussions 使用哪種方式來標定文章, 預設 'pathname'",
  "COMMENT_GISCUS_STRICT": "是否使用严格标题匹配 '1' 开启 '0' 关闭, 预设 '0'",
  "COMMENT_GISCUS_REACTIONS_ENABLED": "你的 Giscus 是否開啟文章表情符號 '1' 開啟 \"0\" 關閉 預設開啟",
  "COMMENT_GISCUS_EMIT_METADATA": "你的 Giscus 是否提取 Metadata '1' 開啟 '0' 關閉 預設關閉",
  "COMMENT_GISCUS_INPUT_POSITION": "你的 Giscus 發表留言位置 'bottom' 尾部 'top' 頂部, 預設 'bottom'",
  "COMMENT_GISCUS_LANG": "你的 Giscus 語言 e.g 'en', 'zh-TW', 'zh-CN', 預設 'en'",
  "COMMENT_GISCUS_LOADING": "你的 Giscus 載入是否漸進式載入, 預設 'lazy'",
  "COMMENT_GISCUS_CROSSORIGIN": "你的 Giscus 可以跨網域, 預設 'anonymous'",
  "COMMENT_CUSDIS_APP_ID": "data-app-id 36位 see https://cusdis.com/",
  "COMMENT_CUSDIS_HOST": "cusdis.com', // data-host, change this if you're using self-hosted version",
  "COMMENT_CUSDIS_SCRIPT_SRC": "change this if you're using self-hosted version",
  "COMMENT_GITALK_REPO": "你的Github仓库名，例如 'NotionNext'",
  "COMMENT_GITALK_OWNER": "你的用户名 e.g tangly1024",
  "COMMENT_GITALK_ADMIN": "管理员用户名、一般是自己 e.g 'tangly1024'",
  "COMMENT_GITALK_DISTRACTION_FREE_MODE": "类似facebook的无干扰模式",
  "COMMENT_GITTER_ROOM": "gitter聊天室 see https://gitter.im/ 不需要则留空",
  "COMMENT_DAO_VOICE_ID": "DaoVoice http://dashboard.daovoice.io/get-started",
  "COMMENT_TIDIO_ID": "[tidio_id] -> //code.tidio.co/[tidio_id].js",
  "COMMENT_VALINE_APP_ID": "Valine @see https://valine.js.org/quickstart.html 或 https://github.com/stonehank/react-valine#%E8%8E%B7%E5%8F%96app-id-%E5%92%8C-app-key",
  "COMMENT_VALINE_SERVER_URLS": "该配置适用于国内自定义域名用户, 海外版本会自动检测(无需手动填写) @see https://valine.js.org/configuration.html#serverURLs",
  "COMMENT_VALINE_PLACEHOLDER": "可以搭配后台管理评论 https://github.com/DesertsP/Valine-Admin  便于查看评论，以及邮件通知，垃圾评论过滤等功能",
  "COMMENT_WALINE_SERVER_URL": "请配置完整的Waline评论地址 例如 hhttps://preview-waline.tangly1024.com @see https://waline.js.org/guide/get-started.html",
  "COMMENT_WALINE_RECENT": "最新评论",
  "CONTACT_WEIBO": "你的微博个人主页",
  "CONTACT_TWITTER": "你的twitter个人主页",
  "CONTACT_GITHUB": "你的github个人主页 例如 https://github.com/tangly1024",
  "CONTACT_TELEGRAM": "你的telegram 地址 例如 https://t.me/tangly_1024",
  "CONTACT_LINKEDIN": "你的linkedIn 首页",
  "CONTACT_ORCID": "ORCID 主页，例如 https://orcid.org/1234-1234-1234-1234",
  "CONTACT_INSTAGRAM": "您的instagram地址",
  "CONTACT_BILIBILI": "B站主页",
  "CONTACT_YOUTUBE": "Youtube主页",
  "CONTACT_XIAOHONGSHU": "小红书主页",
  "CONTACT_ZHISHIXINGQIU": "知识星球",
  "CONTACT_WEHCHAT_PUBLIC": "微信公众号 格式：https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=【xxxxxx】==#wechat_redirect",
  "SUB_PATH": "leave this empty unless you want to deploy in a folder",
  "DEBUG": "是否显示调试按钮",
  "BACKGROUND_LIGHT": "use hex value, don't forget '#' e.g #fffefc",
  "BACKGROUND_DARK": "use hex value, don't forget '#'",
  "BUNDLE_ANALYZER": "是否展示编译依赖内容与大小",
  "NOTION_HOST": "www.notion.so', // Notion域名，您可以选择用自己的域名进行反向代理，如果不懂得什么是反向代理，请勿修改此项",
  "IMAGE_COMPRESS_WIDTH": "图片压缩宽度默认值，作用于博客封面和文章内容 越小加载图片越快",
  "IMAGE_ZOOM_IN_WIDTH": "文章图片点击放大后的画质宽度，不代表在网页中的实际展示宽度",
  "IMAGE_COMPRESS_QUALITY": "图片压缩质量 0-100，数值越小文件越小但质量越低",
  "RANDOM_IMAGE_URL": "随机图片API,如果未配置下面的关键字，主页封面，头像，文章封面图都会被替换为随机图片",
  "IMG_URL_TYPE": "此配置已失效，请勿使用；AMAZON方案不再支持，仅支持Notion方案。 ['Notion','AMAZON'] 站点图片前缀 默认 Notion:(https://notion.so/images/xx) ， AMAZON(https://s3.us-west-2.amazonaws.com/xxx)",
  "IMG_SHADOW": "文章图片是否自动添加阴影",
  "IMG_COMPRESS_WIDTH": "Notion图片压缩宽度",
  "NOTION_INDEX": "默认取Notion数据库中的第1个视图",
  "NOTION_TOKEN_V2": "Useful if you prefer not to make your database public",
  "CHUNK_SIZE_LIMIT": "244KB",
  "BROWSER_CACHE_TTL": "24小时",
  "CDN_CACHE_TTL": "7天",
  "FCP": "First Contentful Paint (ms)",
  "LCP": "Largest Contentful Paint (ms)",
  "FID": "First Input Delay (ms)",
  "CLS": "Cumulative Layout Shift",
  "ALGOLIA_APP_ID": "在这里查看 https://dashboard.algolia.com/account/api-keys/",
  "ALGOLIA_ADMIN_APP_KEY": "管理后台的KEY，不要暴露在代码中，在这里查看 https://dashboard.algolia.com/account/api-keys/",
  "ALGOLIA_SEARCH_ONLY_APP_KEY": "客户端搜索用的KEY",
  "ALGOLIA_INDEX": "在Algolia中创建一个index用作数据库",
  "MAILCHIMP_LIST_ID": "开启mailichimp邮件订阅 客户列表ID ，具体使用方法参阅文档",
  "MAILCHIMP_API_KEY": "开启mailichimp邮件订阅 APIkey",
  "POST_SCHEDULE_PUBLISH": "按照文章的发布时间字段，控制自动上下架",
  "POST_SHARE_BAR_ENABLE": "文章底部分享条开关",
  "POST_TITLE_ICON": "是否显示标题icon",
  "POST_DISABLE_GALLERY_CLICK": "画册视图禁止点击，方便在友链页面的画册插入链接",
  "POST_LIST_STYLE": "['page','scroll'] 文章列表样式:页码分页、单页滚动加载",
  "POST_LIST_PREVIEW": "是否在列表加载文章预览",
  "POST_PREVIEW_LINES": "预览博客行数",
  "POST_RECOMMEND_COUNT": "推荐文章数量",
  "LATEST_POST_COUNT": "最新文章数量",
  "POSTS_PER_PAGE": "post counts per page",
  "POSTS_SORT_BY": "排序方式 'date'按时间,'notion'由notion控制",
  "ARTICLE_EXPIRATION_DAYS": "文章过期提醒阈值（天）",
  "ARTICLE_EXPIRATION_ENABLED": "是否启用文章过期提醒",
  "ORIGINALITY_PROOF_ENABLE": "原创存证：生成并展示文章内容哈希，默认关闭",
  "ORIGINALITY_PROOF_AUTO_MANIFEST": "原创存证：构建时自动生成 public/proofs/originality.json",
  "POST_WAITING_TIME_FOR_404": "文章加载超时时间，单位秒；超时后跳转到404页面",
  "TAG_SORT_BY_COUNT": "标签是否按照文章数量倒序排列，文章多的标签排在前。",
  "IS_TAG_COLOR_DISTINGUISHED": "对于名称相同的tag是否区分tag的颜色",
  "CUSTOM_RIGHT_CLICK_CONTEXT_MENU": "自定义右键菜单，覆盖系统菜单",
  "CUSTOM_RIGHT_CLICK_CONTEXT_MENU_DARK_MODE": "是否显示深色模式",
  "CUSTOM_RIGHT_CLICK_CONTEXT_MENU_SHARE_LINK": "是否显示分享链接",
  "CUSTOM_RIGHT_CLICK_CONTEXT_MENU_RANDOM_POST": "是否显示随机博客",
  "CUSTOM_RIGHT_CLICK_CONTEXT_MENU_CATEGORY": "是否显示分类",
  "CUSTOM_RIGHT_CLICK_CONTEXT_MENU_TAG": "是否显示标签",
  "THEME_SWITCH": "是否显示切换主题按钮",
  "WIDGET_PET": "是否显示宠物挂件",
  "WIDGET_PET_SWITCH_THEME": "点击宠物挂件切换博客主题",
  "SPOILER_TEXT_TAG": "Spoiler文本隐藏功能，如Notion中 [sp]希望被spoiler的文字[sp]，填入[sp] 即可",
  "MUSIC_PLAYER": "是否使用音乐播放插件",
  "MUSIC_PLAYER_VISIBLE": "是否在左下角显示播放和切换，如果使用播放器，打开自动播放再隐藏，就会以类似背景音乐的方式播放，无法取消和暂停",
  "MUSIC_PLAYER_AUTO_PLAY": "是否自动播放，不过自动播放时常不生效（移动设备不支持自动播放）",
  "MUSIC_PLAYER_LRC_TYPE": "歌词显示类型，可选值： 3 | 1 | 0（0：禁用 lrc 歌词，1：lrc 格式的字符串，3：lrc 文件 url）（前提是有配置歌词路径，对 meting 无效）",
  "MUSIC_PLAYER_ORDER": "默认播放方式，顺序 list，随机 random",
  "MUSIC_PLAYER_METING": "是否要开启 MetingJS，从平台获取歌单。会覆盖自定义的 MUSIC_PLAYER_AUDIO_LIST，更多配置信息：https://github.com/metowolf/MetingJS",
  "MUSIC_PLAYER_METING_SERVER": "音乐平台，[netease, tencent, kugou, xiami, baidu]",
  "MUSIC_PLAYER_METING_ID": "对应歌单的 id",
  "MUSIC_PLAYER_METING_LRC_TYPE": "已废弃！！！可选值： 3 | 1 | 0（0：禁用 lrc 歌词，1：lrc 格式的字符串，3：lrc 文件 url）",
  "FACEBOOK_PAGE_TITLE": "邊欄 Facebook Page widget 的標題欄，填''則無標題欄 e.g FACEBOOK 粉絲團'",
  "FACEBOOK_PAGE": "Facebook Page 的連結 e.g https://www.facebook.com/tw.andys.pro",
  "FACEBOOK_PAGE_ID": "Facebook Page ID 來啟用 messenger 聊天功能",
  "FACEBOOK_APP_ID": "Facebook App ID 來啟用 messenger 聊天功能 获取: https://developers.facebook.com/",
  "CLAUDE_POST_AD_ENABLE": "文章列表是否插入广告",
  "CLAUDE_POST_COVER_ENABLE": "是否展示博客封面",
  "CLAUDE_ARTICLE_RECOMMEND_POSTS": "文章详情底部显示推荐",
  "CLAUDE_MENU_CATEGORY": "显示分类",
  "CLAUDE_MENU_TAG": "显示标签",
  "CLAUDE_MENU_ARCHIVE": "显示归档",
  "CLAUDE_TOC_ENABLE": "是否显示目录，默认开启",
  "CLAUDE_TOC_SHOW_LEVEL3": "是否显示第三级目录，默认开启; 设为 false 只显示 L1+L2",
  "CLAUDE_TOC_SCROLL_BEHAVIOR": "滚动行为：'smooth' 或 'instant'",
  "CLAUDE_SUBTITLE_DARK_ONLY": "副标题在浅色和深色模式下都显示，设为 true 则仅深色模式",
  "CLAUDE_PROFILE_AVATAR": "头像URL；留空则回退到 AVATAR/siteInfo.icon",
  "CLAUDE_FOOTER_COPYRIGHT": "例如：© 2023-2026 Yicheng；留空则使用 SINCE + AUTHOR",
  "COMMERCE_TEXT_CENTER_TITLE": "中间产品区块标题",
  "COMMERCE_TEXT_CENTER_DESCRIPTION": "中间产品区块文字描述",
  "COMMERCE_TEXT_CENTER_CATEGORY_TITLE": "左侧产品分类标题",
  "COMMERCE_TEXT_FOOTER_TITLE": "COMMERCE主题页脚文案标题；按Shift+Enter键可以换行",
  "COMMERCE_TEXT_FOOTER_MENU_1": "COMMERCE主题页脚左侧菜单标题1",
  "COMMERCE_TEXT_FOOTER_MENU_2": "COMMERCE主题页脚左侧菜单标题2",
  "COMMERCE_FOOTER_RIGHT_IMG_URL": "显示页脚右侧的图片，通常放二维码",
  "COMMERCE_FOOTER_RIGHT_TEXT": "页脚右侧图片下的文字描述",
  "COMMERCE_HOME_POSTS_COUNT": "首页展示商品数",
  "COMMERCE_CONTACT_WHATSAPP_SHOW": "是否展示whatsapp联系按钮 请配置 CONTACT_WHATSAPP",
  "COMMERCE_CONTACT_TELEGRAM_SHOW": "联系栏展示telegram按钮 请配置 CONTACT_TELEGRAM",
  "COMMERCE_ARTICLE_COPYRIGHT": "文章版权声明",
  "COMMERCE_ARTICLE_NOT_BY_AI": "显示非AI写作",
  "ENDSPACE_LOADING_COVER": "是否显示加载动画",
  "ENDSPACE_LOADING_SITE_NAME": "站点名称，显示在加载动画右侧",
  "ENDSPACE_LOADING_TEXT_INIT": "初始化阶段显示的文字",
  "ENDSPACE_LOADING_TEXT_LOADING": "加载阶段显示的文字",
  "ENDSPACE_LOADING_TEXT_COMPLETE": "加载完成阶段显示的文字",
  "ENDSPACE_LOADING_TEXT_SWEEPING": "扫描阶段显示的文字",
  "ENDSPACE_LOADING_TEXT_FADEOUT": "淡出阶段显示的文字",
  "ENDSPACE_LOADING_IMAGE": "加载动画中显示的图片（默认使用站点 favicon SVG）",
  "ENDSPACE_MENU_CATEGORY": "显示分类菜单（默认合并到 Archive）",
  "ENDSPACE_MENU_TAG": "显示标签菜单（默认合并到 Archive）",
  "ENDSPACE_MENU_ARCHIVE": "显示归档菜单",
  "ENDSPACE_MENU_SEARCH": "显示搜索菜单（默认合并到 Archive）",
  "ENDSPACE_POST_LIST_COVER": "文章列表是否显示封面图",
  "ENDSPACE_POST_LIST_PREVIEW": "文章列表是否显示摘要预览",
  "ENDSPACE_ARTICLE_LAYOUT_VERTICAL": "文章页是否使用垂直布局",
  "ENDSPACE_ARTICLE_ADJACENT": "是否显示上一篇/下一篇文章导航",
  "EXAMPLE_MENU_CATEGORY": "显示分类",
  "EXAMPLE_MENU_TAG": "显示标签",
  "EXAMPLE_MENU_ARCHIVE": "显示归档",
  "EXAMPLE_MENU_SEARCH": "显示搜索",
  "EXAMPLE_POST_LIST_COVER": "列表显示文章封面",
  "EXAMPLE_TITLE_IMAGE": "标题栏，是否背景图片",
  "EXAMPLE_ARTICLE_LAYOUT_VERTICAL": "文章详情，左右布局改为上下布局",
  "EXAMPLE_ARTICLE_HIDDEN_NOTIFICATION": "文章详情隐藏公告",
  "FUKASAWA_MAILCHIMP_FORM": "邮件订阅表单",
  "FUKASAWA_POST_LIST_COVER": "文章列表显示图片封面",
  "FUKASAWA_POST_LIST_COVER_FORCE": "即使没有封面也将站点背景图设置为封面",
  "FUKASAWA_POST_LIST_PREVIEW": "显示文章预览",
  "FUKASAWA_POST_LIST_ANIMATION": "博客列表淡入动画",
  "FUKASAWA_MENU_CATEGORY": "显示分类",
  "FUKASAWA_MENU_TAG": "显示标签",
  "FUKASAWA_MENU_ARCHIVE": "显示归档",
  "FUKASAWA_SIDEBAR_COLLAPSE_BUTTON": "侧边栏折叠按钮",
  "FUKASAWA_SIDEBAR_COLLAPSE_SATUS_DEFAULT": "侧边栏默认折叠收起",
  "FUKASAWA_SIDEBAR_COLLAPSE_ON_SCROLL": "侧边栏滚动时折叠 仅文章阅读页有效",
  "FUWARI_CONTACT_URL": "docs.tangly1024.com/article/chat-community',",
  "GAME_NAV_NOTION_ICON": "是否读取Notion图标作为站点头像 ; 否则默认显示黑色SVG方块",
  "GAME_RECOMMEND_TAG": "打了此Tag，被视为推荐",
  "GAME_INDEX_EXPAND_RECOMMEND": "首页列表是否将推荐游戏放大，否则随机放大。",
  "GAME_MENU_RANDOM_POST": "是否显示随机跳转文章按钮",
  "GAME_MENU_SEARCH_BUTTON": "是否显示搜索按钮，该按钮支持Algolia搜索",
  "GAME_MENU_CATEGORY": "显示分类",
  "GAME_MENU_TAG": "显示标签",
  "GAME_MENU_ARCHIVE": "显示归档",
  "GAME_MENU_SEARCH": "显示搜索",
  "GAME_MENU_RSS": "显示订阅",
  "GITBOOK_INDEX_PAGE": "文档首页显示的文章，请确此路径包含在您的notion数据库中",
  "GITBOOK_AUTO_SORT": "是否自动按分类名 归组排序文章；自动归组可能会打乱您Notion中的文章顺序",
  "GITBOOK_LATEST_POST_RED_BADGE": "是否给最新文章显示红点",
  "GITBOOK_MENU_CATEGORY": "显示分类",
  "GITBOOK_BOOK_MENU_TAG": "显示标签",
  "GITBOOK_MENU_ARCHIVE": "显示归档",
  "GITBOOK_MENU_SEARCH": "显示搜索",
  "GITBOOK_EXCLUSIVE_COLLAPSE": "一次只展开一个分类，其它文件夹自动关闭。",
  "GITBOOK_FOLDER_HOVER_EXPAND": "左侧导航文件夹鼠标悬停时自动展开；若为false，则要点击才能展开",
  "GITBOOK_WIDGET_REVOLVER_MAPS": "地图插件",
  "GITBOOK_WIDGET_TO_TOP": "跳回顶部",
  "HEO_HOME_POST_TWO_COLS": "首页博客两列显示，若为false则只显示一列",
  "HEO_LOADING_COVER": "页面加载的遮罩动画",
  "HEO_INFO_CARD_AVATAR_BLUR": "文章详情页个人资料卡头像样式。true：显示为模糊装饰头像；false：与首页头像保持一致",
  "HEO_SITE_CREATE_TIME": "建站日期，用于计算网站运行的第几天",
  "HEO_HERO_TITLE_LINK": "tangly1024.com',",
  "HEO_HERO_RECOMMEND_POST_SORT_BY_UPDATE_TIME": "推荐文章排序，为`true`时将强制按最后修改时间倒序",
  "HEO_HERO_RECOMMEND_COVER_ENABLE": "是否显示推荐文章遮罩图片，true显示遮罩需点击查看，false直接显示推荐文章",
  "HEO_INFO_CARD_URL2": "github.com/tangly1024',",
  "HEO_INFO_CARD_URL3": "www.tangly1024.com',",
  "HEO_SOCIAL_CARD": "是否显示右侧，点击加入社群按钮",
  "HEO_SOCIAL_CARD_URL": "docs.tangly1024.com/article/how-to-question',",
  "HEO_MENU_INDEX": "显示首页",
  "HEO_MENU_CATEGORY": "显示分类",
  "HEO_MENU_TAG": "显示标签",
  "HEO_MENU_ARCHIVE": "显示归档",
  "HEO_MENU_SEARCH": "显示搜索",
  "HEO_POST_LIST_COVER": "列表显示文章封面",
  "HEO_POST_LIST_COVER_HOVER_ENLARGE": "列表鼠标悬停放大",
  "HEO_POST_LIST_COVER_DEFAULT": "封面为空时用站点背景做默认封面",
  "HEO_POST_LIST_SUMMARY": "文章摘要",
  "HEO_POST_LIST_PREVIEW": "读取文章预览",
  "HEO_POST_LIST_IMG_CROSSOVER": "博客列表图片左右交错",
  "HEO_ARTICLE_ADJACENT": "显示上一篇下一篇文章推荐",
  "HEO_ARTICLE_COPYRIGHT": "文章版权声明：true 全部显示；false 全部关闭；custom 仅填写 copyright 时显示",
  "HEO_ARTICLE_NOT_BY_AI": "显示非AI写作",
  "HEO_ARTICLE_RECOMMEND": "文章关联推荐",
  "HEO_WIDGET_LATEST_POSTS": "显示最新文章卡",
  "HEO_WIDGET_ANALYTICS": "显示统计卡",
  "HEO_WIDGET_TO_COMMENT": "跳到评论区",
  "HEO_WIDGET_DARK_MODE": "夜间模式",
  "HEO_WIDGET_TOC": "移动端悬浮目录",
  "HEXO_HOME_NAV_BUTTONS": "首页是否显示分类大图标按钮",
  "HEXO_HOME_NAV_BACKGROUND_IMG_FIXED": "首页背景图滚动时是否固定，true 则滚动时图片不懂动； false则随鼠标滚动 ;",
  "HEXO_MENU_INDEX": "显示首页",
  "HEXO_MENU_CATEGORY": "显示分类",
  "HEXO_MENU_TAG": "显示标签",
  "HEXO_MENU_ARCHIVE": "显示归档",
  "HEXO_MENU_SEARCH": "显示搜索",
  "HEXO_MENU_RANDOM": "显示随机跳转按钮",
  "HEXO_POST_LIST_COVER": "列表显示文章封面",
  "HEXO_POST_LIST_COVER_HOVER_ENLARGE": "列表鼠标悬停放大",
  "HEXO_POST_LIST_COVER_DEFAULT": "封面为空时用站点背景做默认封面",
  "HEXO_POST_LIST_SUMMARY": "文章摘要",
  "HEXO_POST_LIST_PREVIEW": "读取文章预览",
  "HEXO_POST_LIST_IMG_CROSSOVER": "博客列表图片左右交错",
  "HEXO_ARTICLE_ADJACENT": "显示上一篇下一篇文章推荐",
  "HEXO_ARTICLE_COPYRIGHT": "文章版权声明：true 全部显示；false 全部关闭；custom 仅填写 copyright 时显示",
  "HEXO_ARTICLE_NOT_BY_AI": "显示非AI写作",
  "HEXO_ARTICLE_RECOMMEND": "文章关联推荐",
  "HEXO_WIDGET_LATEST_POSTS": "显示最新文章卡",
  "HEXO_WIDGET_ANALYTICS": "显示统计卡",
  "HEXO_WIDGET_TO_COMMENT": "跳到评论区",
  "HEXO_WIDGET_DARK_MODE": "夜间模式",
  "HEXO_WIDGET_TOC": "移动端悬浮目录",
  "HEXO_THEME_COLOR": "主题色配置（默认为 #928CEE）",
  "LANDING_HEADER_BUTTON_1_URL": "github.com/notionnext-org/NotionNext',",
  "LANDING_HEADER_BUTTON_2_URL": "blog.tangly1024.com/',",
  "LANDING_HERO_BUTTON_1_LINK": "docs.tangly1024.com/article/vercel-deploy-notion-next',",
  "LANDING_HERO_BUTTON_2_LINK": "docs.tangly1024.com/about',",
  "LANDING_HERO_VIDEO_IFRAME": "player.bilibili.com/player.html?aid=913088616&bvid=BV1fM4y1L7Qi&cid=1187218697&page=1&&high_quality=1',",
  "LANDING_TESTIMONIALS_AVATAR": "www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F22de3fcb-d90d-4271-bc01-f815f476122b%2F4FE0A0C0-E487-4C74-BF8E-6F01A27461B8-14186-000008094BC289A6.jpg?table=collection&id=a320a2cc-6ebe-4a8d-95cc-ea94e63bced9&width=200',",
  "LANDING_TESTIMONIALS_SOCIAL_URL": "blog.gaoran.xyz/',",
  "LANDING_POST_REDIRECT_ENABLE": "是否开启文章地址重定向 ； 用于迁移旧网站域名",
  "LANDING_POST_REDIRECT_URL": "blog.tangly1024.com', // 重定向网站地址",
  "LANDING_PRICING_1_URL": "docs.tangly1024.com/about',",
  "LANDING_PRICING_2_URL": "tangly1024.lemonsqueezy.com/checkout/buy/0adb9153-0799-4f51-91aa-1f06391ea4e0',",
  "LANDING_PRICING_3_URL": "tangly1024.lemonsqueezy.com/checkout/buy/df924d66-09dc-42a4-a632-a6b0c5cc4f28',",
  "LANDING_NEWSLETTER": "是否开启邮件订阅 请先配置mailchimp功能 https://docs.tangly1024.com/article/notion-next-mailchimp",
  "MAGZINE_HOME_BANNER_ENABLE": "首屏右上角的宣传位",
  "MAGZINE_HOME_HIDDEN_CATEGORY": "不希望在首页展示的文章分类，用英文逗号隔开",
  "MAGZINE_HERO_SUB_POST_COUNT": "首屏英雄区次要文章数量，通常2篇，如果关闭Banner，推荐改为3篇",
  "MAGZINE_RECOMMEND_POST_SORT_BY_UPDATE_TIME": "推荐文章排序，为`true`时将强制按最后修改时间倒序",
  "MAGZINE_RIGHT_PANEL_DARK": "右侧面板深色模式",
  "MAGZINE_POST_LIST_COVER": "文章列表显示图片封面",
  "MAGZINE_POST_LIST_PREVIEW": "列表显示文章预览",
  "MAGZINE_POST_LIST_CATEGORY": "列表显示文章分类",
  "MAGZINE_POST_LIST_TAG": "列表显示文章标签",
  "MAGZINE_POST_DETAIL_CATEGORY": "文章显示分类",
  "MAGZINE_POST_DETAIL_TAG": "文章显示标签",
  "MAGZINE_SOCIAL_CARD": "是否显示右侧，点击加入社群按钮",
  "MAGZINE_SOCIAL_CARD_URL": "docs.tangly1024.com/article/chat-community',",
  "MAGZINE_MENU_CATEGORY": "显示分类",
  "MAGZINE_MENU_TAG": "显示标签",
  "MAGZINE_MENU_ARCHIVE": "显示归档",
  "MAGZINE_MENU_SEARCH": "显示搜索",
  "MAGZINE_WIDGET_TO_TOP": "跳回顶部",
  "MATERY_HOME_NAV_BUTTONS": "首页是否显示分类大图标按钮",
  "MATERY_HOME_NAV_BACKGROUND_IMG_FIXED": "首页背景图滚动时是否固定，true 则滚动时图片不懂； false则随鼠标滚动",
  "MATERY_MENU_CATEGORY": "显示分类",
  "MATERY_MENU_TAG": "显示标签",
  "MATERY_MENU_ARCHIVE": "显示归档",
  "MATERY_MENU_SEARCH": "显示搜索",
  "MATERY_POST_LIST_COVER": "文章封面",
  "MATERY_POST_LIST_SUMMARY": "文章摘要",
  "MATERY_POST_LIST_PREVIEW": "读取文章预览",
  "MATERY_ARTICLE_ADJACENT": "显示上一篇下一篇文章推荐",
  "MATERY_ARTICLE_COPYRIGHT": "文章版权声明：true 全部显示；false 全部关闭；custom 仅填写 copyright 时显示",
  "MATERY_ARTICLE_NOT_BY_AI": "显示非AI写作",
  "MATERY_ARTICLE_RECOMMEND": "文章关联推荐",
  "MATERY_WIDGET_LATEST_POSTS": "显示最新文章卡",
  "MATERY_WIDGET_ANALYTICS": "显示统计卡",
  "MATERY_WIDGET_TO_COMMENT": "跳到评论区",
  "WIDGET_DARK_MODE": "夜间模式",
  "MATERY_WIDGET_TOC": "移动端悬浮目录",
  "MEDIUM_RIGHT_PANEL_DARK": "右侧面板深色模式",
  "MEDIUM_POST_LIST_COVER": "文章列表显示图片封面",
  "MEDIUM_POST_LIST_PREVIEW": "列表显示文章预览",
  "MEDIUM_POST_LIST_CATEGORY": "列表显示文章分类",
  "MEDIUM_POST_LIST_TAG": "列表显示文章标签",
  "MEDIUM_POST_DETAIL_CATEGORY": "文章显示分类",
  "MEDIUM_POST_DETAIL_TAG": "文章显示标签",
  "MEDIUM_MENU_CATEGORY": "显示分类",
  "MEDIUM_MENU_TAG": "显示标签",
  "MEDIUM_MENU_ARCHIVE": "显示归档",
  "MEDIUM_MENU_SEARCH": "显示搜索",
  "MEDIUM_WIDGET_REVOLVER_MAPS": "地图插件",
  "MEDIUM_WIDGET_TO_TOP": "跳回顶部",
  "MOVIE_MENU_CATEGORY": "显示分类",
  "MOVIE_MENU_TAG": "显示标签",
  "MOVIE_MENU_ARCHIVE": "显示归档",
  "MOVIE_MENU_SEARCH": "显示搜索",
  "MOVIE_HOME_BACKGROUND": "首页是否显示背景图, 默认关闭",
  "MOVIE_PREVIEW_CATEGORY_COUNT": "首页最多展示的分类数量，0为不限制",
  "MOVIE_ARTICLE_RECOMMEND": "推荐关联内容在文章底部",
  "MOVIE_VIDEO_COMBINE": "聚合视频，开启后一篇文章内的多个含caption的视频会被合并到文章开头，并展示分集按钮",
  "MOVIE_VIDEO_COMBINE_SHOW_PAGE_FORCE": "即使只有一集也显示集数切换按钮",
  "MOVIE_POST_LIST_COVER": "列表显示文章封面",
  "NAV_INDEX_PAGE": "文档首页显示的文章，请确此路径包含在您的notion数据库中",
  "NAV_AUTO_SORT": "是否自动按分类名 归组排序文章；自动归组可能会打乱您Notion中的文章顺序",
  "NAV_SHOW_TITLE_TEXT": "标题栏显示文本",
  "NAV_USE_CUSTOM_MENU": "使用自定义菜单（可支持子菜单，支持自定义分类图标），若为true则显示所有的category分类",
  "NAV_MENU_CATEGORY": "显示分类",
  "NAV_MENU_TAG": "显示标签",
  "NAV_MENU_ARCHIVE": "显示归档",
  "NAV_MENU_SEARCH": "显示搜索",
  "NAV_WIDGET_REVOLVER_MAPS": "地图插件",
  "NAV_WIDGET_TO_TOP": "跳回顶部",
  "NEXT_HOME_BANNER": "首页是否显示大图及标语 [true,false]",
  "NEXT_NAV_TYPE": "['fixed','autoCollapse','normal'] 分别是固定屏幕顶部并始终显示、固定屏幕顶部且滚动时隐藏，不固定屏幕顶部",
  "NEXT_POST_LIST_COVER": "文章列表显示封面图",
  "NEXT_POST_LIST_PREVIEW": "显示文章预览",
  "NEXT_POST_LIST_SUMMARY": "显示用户自定义摘要，有预览时优先只展示预览",
  "NEXT_PREVIEW_TAG_COUNT": "首页最多展示的标签数量，0为不限制",
  "NEXT_PREVIEW_CATEGORY_COUNT": "首页最多展示的分类数量，0为不限制",
  "NEXT_POST_HEADER_IMAGE_VISIBLE": "文章详情页是否显示封面图",
  "NEXT_RIGHT_BAR": "是否显示右侧栏",
  "NEXT_RIGHT_LATEST_POSTS": "右侧栏最新文章",
  "NEXT_RIGHT_CATEGORY_LIST": "右侧边栏文章分类列表",
  "NEXT_RIGHT_TAG_LIST": "右侧边栏标签分类列表",
  "NEXT_RIGHT_AD": "右侧广告",
  "NEXT_MENU_HOME": "显示首页",
  "NEXT_MENU_CATEGORY": "显示分类",
  "NEXT_MENU_TAG": "显示标签",
  "NEXT_MENU_ARCHIVE": "显示归档",
  "NEXT_MENU_SEARCH": "显示搜索",
  "NEXT_WIDGET_TO_TOP": "是否显示回顶",
  "NEXT_WIDGET_TO_BOTTOM": "显示回底",
  "NEXT_WIDGET_DARK_MODE": "显示日间/夜间模式切换",
  "NEXT_WIDGET_TOC": "移动端显示悬浮目录",
  "NEXT_ARTICLE_RELATE_POSTS": "相关文章推荐",
  "NEXT_ARTICLE_COPYRIGHT": "文章版权声明：true 全部显示；false 全部关闭；custom 仅填写 copyright 时显示",
  "NEXT_ARTICLE_NOT_BY_AI": "显示非AI写作",
  "NEXT_ARTICLE_INFO": "显示文章信息",
  "NOBELIUM_NAV_NOTION_ICON": "是否读取Notion图标作为站点头像 ; 否则默认显示黑色SVG方块",
  "NOBELIUM_MENU_RANDOM_POST": "是否显示随机跳转文章按钮",
  "NOBELIUM_MENU_SEARCH_BUTTON": "是否显示搜索按钮，该按钮支持Algolia搜索",
  "NOBELIUM_MENU_DARKMODE_BUTTON": "菜单显示深色模式切换",
  "NOBELIUM_MENU_CATEGORY": "显示分类",
  "NOBELIUM_MENU_TAG": "显示标签",
  "NOBELIUM_MENU_ARCHIVE": "显示归档",
  "NOBELIUM_MENU_SEARCH": "显示搜索",
  "NOBELIUM_MENU_RSS": "显示订阅",
  "NOBELIUM_AUTO_COLLAPSE_NAV_BAR": "页头导航栏动画",
  "OPC_NAME": "顶部名称",
  "OPC_KICKER": "首屏标签",
  "OPC_TITLE": "主标题",
  "OPC_SUBTITLE": "副标题",
  "OPC_DESCRIPTION": "主介绍",
  "OPC_PRIMARY_TEXT": "主按钮文字",
  "OPC_PRIMARY_URL": "preview.tangly1024.com', // 主按钮链接",
  "OPC_SECONDARY_TEXT": "副按钮文字",
  "OPC_SECONDARY_URL": "blog.tangly1024.com', // 副按钮链接",
  "OPC_STATUS_TEXT": "状态标签",
  "OPC_CARD_TITLE": "工作流卡片标题",
  "OPC_CARD_DESCRIPTION": "工作流说明",
  "OPC_NOW_TITLE": "近况标题",
  "OPC_NOW_DESCRIPTION": "近况说明",
  "OPC_NOW_ITEMS": "近况标签，英文逗号分隔",
  "OPC_COLOR_PRIMARY": "浅色主色",
  "OPC_COLOR_BG": "浅色页面背景",
  "OPC_COLOR_CARD": "浅色卡片背景",
  "OPC_COLOR_TEXT": "浅色主文字",
  "OPC_COLOR_TEXT_SECONDARY": "浅色次级文字",
  "OPC_COLOR_BORDER": "浅色边框",
  "OPC_COLOR_PRIMARY_DARK": "深色主色",
  "OPC_COLOR_BG_DARK": "深色页面背景",
  "OPC_COLOR_CARD_DARK": "深色卡片背景",
  "OPC_COLOR_TEXT_DARK": "深色主文字",
  "OPC_COLOR_TEXT_SECONDARY_DARK": "深色次级文字",
  "OPC_COLOR_BORDER_DARK": "深色边框",
  "PHOTO_MENU_CATEGORY": "显示分类",
  "PHOTO_MENU_TAG": "显示标签",
  "PHOTO_MENU_ARCHIVE": "显示归档",
  "PHOTO_MENU_SEARCH": "显示搜索",
  "PHOTO_HOME_BACKGROUND": "首页是否显示背景图, 默认关闭",
  "PHOTO_ARTICLE_RECOMMEND": "推荐关联内容在文章底部",
  "PHOTO_VIDEO_COMBINE": "聚合视频，开启后一篇文章内的多个含caption的视频会被合并到文章开头，并展示分集按钮",
  "PHOTO_VIDEO_COMBINE_SHOW_PAGE_FORCE": "即使只有一集也显示集数切换按钮",
  "PHOTO_PREVIEW_CATEGORY_COUNT": "首页最多展示的分类数量，0为不限制",
  "PHOTO_POST_LIST_COVER": "列表显示文章封面",
  "PROXIO_WELCOME_COVER_ENABLE": "是否显示页面进入的欢迎文字",
  "PROXIO_WELCOME_TEXT": "欢迎文字，留空则不启用",
  "PROXIO_HERO_ENABLE": "开启英雄区",
  "PROXIO_HERO_TITLE_1": "英雄区文字",
  "PROXIO_HERO_TITLE_2": "英雄区文字",
  "PROXIO_HERO_BUTTON_1_TEXT": "英雄区按钮",
  "PROXIO_HERO_BUTTON_1_URL": "docs.tangly1024.com/article/vercel-deploy-notion-next', // 英雄区按钮",
  "PROXIO_HERO_BUTTON_2_TEXT": "英雄区按钮",
  "PROXIO_HERO_BUTTON_2_URL": "github.com/notionnext-org/NotionNext', // 英雄区按钮",
  "PROXIO_HERO_BUTTON_2_ICON": "英雄区按钮2的图标，不需要则留空",
  "PROXIO_HERO_BANNER_IMAGE": "hero区背景，默认是获取Notion背景，如需另外配置图片可以填写在这里",
  "PROXIO_HERO_BANNER_IFRAME_URL": "hero背景区内嵌背景网页 ，可以配置一个网页地址，例如动画网页https://my.spline.design/untitled-b0c6e886227646c34afc82cdc6de4ca2/",
  "PROXIO_BLOG_ENABLE": "首页博文区块开关",
  "PROXIO_BLOG_COUNT": "首页博文区块展示前4篇文章",
  "PROXIO_BLOG_AUTO_SHOW_COVER": "首页博文区块是否默认显示文章主图；false 时保持悬浮显示主图的旧效果",
  "PROXIO_BLOG_PLACEHOLDER_IMG_URL_1": "填写要替换成的图片，支持图床或直接上传到项目中，示例  /images/feature-1.webp",
  "PROXIO_ANNOUNCEMENT_ENABLE": "公告文字区块",
  "PROXIO_FEATURE_ENABLE": "特性区块开关",
  "PROXIO_FEATURE_1_ICON_CLASS": "fas图标",
  "PROXIO_FEATURE_1_ICON_IMG_URL": "图片图标选填，默认是fas图标，如果需要图片图标可以填写图片地址，示例/avatar.png",
  "PROXIO_FEATURE_BUTTON_TEXT": "按钮文字",
  "PROXIO_FEATURE_BUTTON_URL": "github.com/notionnext-org/NotionNext', // 按钮跳转",
  "PROXIO_CAREER_ENABLE": "区块开关",
  "PROXIO_TESTIMONIALS_ENABLE": "测评区块开关",
  "PROXIO_TESTIMONIALS_ITEM_AVATAR": "www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F22de3fcb-d90d-4271-bc01-f815f476122b%2F4FE0A0C0-E487-4C74-BF8E-6F01A27461B8-14186-000008094BC289A6.jpg?table=collection&id=a320a2cc-6ebe-4a8d-95cc-ea94e63bced9&width=200',",
  "PROXIO_TESTIMONIALS_ITEM_URL": "blog.gaoran.xyz/'",
  "PROXIO_FAQ_ENABLE": "常见问题模块开关",
  "PROXIO_ABOUT_ENABLE": "关于作者区块区块开关",
  "PROXIO_BRANDS_ENABLE": "滚动文字",
  "PROXIO_CTA_BUTTON": "是否显示按钮",
  "PROXIO_POST_REDIRECT_ENABLE": "默認開啟重定向",
  "PROXIO_POST_REDIRECT_URL": "blog.tangly1024.com', // 重定向域名",
  "PROXIO_NEWSLETTER": "是否开启邮件订阅 请先配置mailchimp功能 https://docs.tangly1024.com/article/notion-next-mailchimp",
  "SIMPLE_TOP_BAR": "显示顶栏",
  "SIMPLE_POST_AD_ENABLE": "文章列表是否插入广告",
  "SIMPLE_POST_COVER_ENABLE": "是否展示博客封面",
  "SIMPLE_ARTICLE_RECOMMEND_POSTS": "文章详情底部显示推荐",
  "SIMPLE_MENU_CATEGORY": "显示分类",
  "SIMPLE_MENU_TAG": "显示标签",
  "SIMPLE_MENU_ARCHIVE": "显示归档",
  "SIMPLE_MENU_SEARCH": "显示搜索",
  "STARTER_LOGO": "普通logo图片 示例：/images/starter/logo/logo.svg",
  "STARTER_LOGO_WHITE": "透明底浅色logo 示例： /images/starter/logo/logo-white.svg",
  "STARTER_HERO_ENABLE": "开启英雄区",
  "STARTER_HERO_TITLE_1": "英雄区文字",
  "STARTER_HERO_TITLE_2": "英雄区文字",
  "STARTER_HERO_BUTTON_1_TEXT": "英雄区按钮",
  "STARTER_HERO_BUTTON_1_URL": "notionnext.tangly1024.com/', // 英雄区按钮",
  "STARTER_HERO_BUTTON_2_TEXT": "英雄区按钮",
  "STARTER_HERO_BUTTON_2_URL": "github.com/notionnext-org/NotionNext', // 英雄区按钮",
  "STARTER_HERO_BUTTON_2_ICON": "英雄区按钮2的图标，不需要则留空",
  "STARTER_HERO_PREVIEW_IMAGE": "产品预览图 ，默认读取public目录下图片",
  "STARTER_HERO_BANNER_IMAGE": "hero区下方的全宽图",
  "STARTER_FEATURE_ENABLE": "特性区块开关",
  "STARTER_FEATURE_TITLE": "特性",
  "STARTER_FEATURE_TEXT_1": "特性",
  "STARTER_FEATURE_TEXT_2": "特性",
  "STARTER_FEATURE_1_TITLE_1": "特性1",
  "STARTER_FEATURE_1_TEXT_1": "特性1",
  "STARTER_FEATURE_1_BUTTON_TEXT": "特性1",
  "STARTER_FEATURE_1_BUTTON_URL": "github.com/notionnext-org/NotionNext', // 特性1",
  "STARTER_FEATURE_2_TITLE_1": "特性2",
  "STARTER_FEATURE_2_TEXT_1": "特性2",
  "STARTER_FEATURE_2_BUTTON_TEXT": "特性2",
  "STARTER_FEATURE_2_BUTTON_URL": "docs.tangly1024.com/article/notion-next-themes', // 特性2",
  "STARTER_FEATURE_3_TITLE_1": "特性3",
  "STARTER_FEATURE_3_TEXT_1": "特性3",
  "STARTER_FEATURE_3_BUTTON_TEXT": "特性3",
  "STARTER_FEATURE_3_BUTTON_URL": "docs.tangly1024.com/article/next-js', // 特性3",
  "STARTER_FEATURE_4_TITLE_1": "特性4",
  "STARTER_FEATURE_4_TEXT_1": "特性4",
  "STARTER_FEATURE_4_BUTTON_TEXT": "特性4",
  "STARTER_FEATURE_4_BUTTON_URL": "docs.tangly1024.com/about', // 特性4",
  "STARTER_ABOUT_ENABLE": "ABOUT区块开关",
  "STARTER_ABOUT_BUTTON_URL": "docs.tangly1024.com/about',",
  "STARTER_PRICING_ENABLE": "价格区块开关",
  "STARTER_PRICING_1_FEATURES": "英文逗号隔开",
  "STARTER_PRICING_1_BUTTON_URL": "tangly1024.lemonsqueezy.com/checkout/buy/c1a38a65-362e-44c5-8065-733fee39eb54',",
  "STARTER_PRICING_2_FEATURES": "英文逗号隔开",
  "STARTER_PRICING_2_BUTTON_URL": "tangly1024.lemonsqueezy.com/checkout/buy/590ad70a-c3b7-4caf-94ec-9ca27bde06d4',",
  "STARTER_PRICING_3_FEATURES": "英文逗号隔开",
  "STARTER_PRICING_3_BUTTON_URL": "tangly1024.lemonsqueezy.com/checkout/buy/df924d66-09dc-42a4-a632-a6b0c5cc4f28',",
  "STARTER_TESTIMONIALS_ENABLE": "测评区块开关",
  "STARTER_TESTIMONIALS_STAR_ICON": "评分图标",
  "STARTER_TESTIMONIALS_ITEM_AVATAR": "www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F22de3fcb-d90d-4271-bc01-f815f476122b%2F4FE0A0C0-E487-4C74-BF8E-6F01A27461B8-14186-000008094BC289A6.jpg?table=collection&id=a320a2cc-6ebe-4a8d-95cc-ea94e63bced9&width=200',",
  "STARTER_TESTIMONIALS_ITEM_URL": "blog.gaoran.xyz/'",
  "STARTER_FAQ_ENABLE": "常见问题模块开关",
  "STARTER_FAQ_1_ANSWER": "docs.tangly1024.com/about\" className=\"underline\">帮助文档</a>，操作<a href=\"https://www.bilibili.com/video/BV1fM4y1L7Qi/\" className=\"underline\">演示视频</a>，以及<a href=\"https://docs.tangly1024.com/article/chat-community\" className=\"underline\">交流社群</a>来协助您完成网站的搭建部署',",
  "STARTER_FAQ_2_ANSWER": "docs.tangly1024.com/article/start-to-write\">《帮助文档》</a>',",
  "STARTER_TEAM_ENABLE": "团队成员区块开关",
  "STARTER_TEAM_TEXT_2": "github.com/notionnext-org/NotionNext/graphs/contributors\">贡献者</a>',",
  "STARTER_TEAM_ITEM_AVATAR": "www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2Fa06c61bb-980e-4180-bc18-c15f92c78bb4%2Ftangly1024.jpg?table=collection&id=8e7acf17-de09-4fa1-abde-b5b80ad4a813&t=8e7acf17-de09-4fa1-abde-b5b80ad4a813&width=100&cache=v2',",
  "STARTER_BLOG_ENABLE": "首页博文区块开关",
  "STARTER_BLOG_COUNT": "首页博文区块默认展示前3篇文章",
  "STARTER_CONTACT_ENABLE": "联系模块开关",
  "STARTER_CONTACT_MSG_EXTERNAL_URL": "noteforms.com/forms/yfctc7', // 基于NoteForm创建，将留言数据存在Notion中",
  "STARTER_BRANDS_ENABLE": "合作伙伴开关",
  "URL": "graygrids.com/',",
  "STARTER_CTA_BUTTON": "是否显示按钮",
  "STARTER_CTA_BUTTON_URL": "notionnext.tangly1024.com/',",
  "STARTER_POST_REDIRECT_ENABLE": "默認開啟重定向",
  "STARTER_POST_REDIRECT_URL": "blog.tangly1024.com', // 重定向域名",
  "STARTER_NEWSLETTER": "是否开启邮件订阅 请先配置mailchimp功能 https://docs.tangly1024.com/article/notion-next-mailchimp",
  "THOUGHTLITE_MENU_CATEGORY": "显示分类",
  "THOUGHTLITE_MENU_TAG": "显示标签",
  "THOUGHTLITE_MENU_ARCHIVE": "显示归档",
  "THOUGHTLITE_MENU_SEARCH": "显示搜索",
  "THOUGHTLITE_POST_LIST_COVER": "时间线模式建议关闭封面以保清爽",
  "THOUGHTLITE_TITLE_IMAGE": "标题栏，是否背景图片",
  "THOUGHTLITE_ARTICLE_LAYOUT_VERTICAL": "文章详情，左右布局改为上下布局",
  "THOUGHTLITE_ARTICLE_HIDDEN_NOTIFICATION": "文章详情隐藏公告",
  "TYPOGRAPHY_POST_AD_ENABLE": "文章列表是否插入广告",
  "TYPOGRAPHY_POST_COVER_ENABLE": "是否展示博客封面",
  "TYPOGRAPHY_ARTICLE_RECOMMEND_POSTS": "文章详情底部显示推荐",
  "TYPOGRAPHY_MENU_CATEGORY": "显示分类",
  "TYPOGRAPHY_MENU_TAG": "显示标签",
  "TYPOGRAPHY_MENU_ARCHIVE": "显示归档",
  "XUHOME_BG_IMAGE": "页面背景图路径；留空则使用纯色背景",
  "XUHOME_HERO_ENABLE": "首页显示 Hero 区",
  "XUHOME_HERO_TEXTS": "打字机轮播文字",
  "XUHOME_HERO_TITLE_COLOR": "Hero 标题颜色",
  "XUHOME_HERO_BIO_COLOR": "Hero 简介颜色",
  "XUHOME_HERO_TYPE_SPEED": "打字速度（毫秒/字）",
  "XUHOME_HERO_DELETE_SPEED": "删除速度（毫秒/字）",
  "XUHOME_HERO_TYPE_PAUSE": "每段文字停留时间（毫秒）",
  "XUHOME_MENU_ARCHIVE": "显示归档入口",
  "XUHOME_MENU_TAG": "显示标签入口",
  "XUHOME_MENU_SEARCH": "显示搜索入口",
  "XUHOME_SIDEBAR": "桌面端显示侧边栏",
  "XUHOME_ARTICLE_RECOMMEND_POSTS": "文章页显示推荐内容",
  "XUHOME_UPTIME_ENABLE": "显示站点运行时长",
  "XUHOME_UPTIME_SINCE": "建站日期（YYYY-MM-DD）"
}
;